# Generated by Django 4.2.7 on 2025-11-24 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanproduct',
            options={},
        ),
        migrations.RenameField(
            model_name='chargemaster',
            old_name='amount',
            new_name='value',
        ),
        migrations.AddField(
            model_name='chargemaster',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.CharField(choices=[('kyc', 'KYC Document'), ('income', 'Income Document'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='charges',
            field=models.ManyToManyField(blank=True, to='adminpanel.chargemaster'),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('car', 'Car Loan'), ('home', 'Home Loan'), ('business', 'Business Loan')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='max_tenure_months',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='min_tenure_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='required_documents',
            field=models.ManyToManyField(blank=True, to='adminpanel.documenttype'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_roles', to='adminpanel.rolemaster'),
        ),
    ]
