# Generated by Django 6.0 on 2025-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolemaster',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
