# Generated by Django 4.2.7 on 2025-12-08 10:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('coupon_code', models.CharField(max_length=100, unique=True)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('created_user', models.CharField(blank=True, max_length=255, null=True)),
                ('modified_user', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('subscription_id', models.ManyToManyField(blank=True, to='adminpanel.subscription')),
            ],
            options={
                'db_table': 'admin_coupons',
            },
        ),
    ]
