# Generated by Django 4.2.7 on 2025-12-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_occupationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('value', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('loan', 'Loan Configuration'), ('system', 'System & Security'), ('notify', 'Notifications & Email')], max_length=20)),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('BOOLEAN', 'Boolean'), ('NUMBER', 'Number')], default='STRING', max_length=20)),
                ('is_encrypted', models.BooleanField(default=False)),
            ],
        ),
    ]
