# Generated by Django 4.2.7 on 2025-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pause', 'Pause'), ('Cancel', 'Cancel')], default='Active', max_length=20),
        ),
    ]
