# Generated by Django 4.2.7 on 2025-12-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_subscription_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tenants', models.IntegerField(default=0)),
                ('tenants_trend', models.CharField(blank=True, max_length=20)),
                ('active_users', models.IntegerField(default=0)),
                ('users_trend', models.CharField(blank=True, max_length=20)),
                ('total_loans', models.IntegerField(default=0)),
                ('loans_trend', models.CharField(blank=True, max_length=20)),
                ('disbursed_amount', models.CharField(blank=True, max_length=50)),
                ('amount_trend', models.CharField(blank=True, max_length=20)),
                ('monthly_disbursement', models.JSONField(blank=True, default=list)),
                ('loan_status_distribution', models.JSONField(blank=True, default=list)),
                ('recent_activity', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
            },
        ),
    ]
